# Generated by Django 4.0.3 on 2022-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_alter_tickets_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='archive_root',
            field=models.FileField(upload_to='archives/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='image_root',
            field=models.FileField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='pdf_root',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
